In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
from functions import (
    QR3primes,
    extended_generator_matrix,
    generator_matrix,
    delta_divisible,
    delta_divisible_np,
    min_distance_brute,
    triorthogonal
)

In [ ]:
prime_list = QR2primes(150)
print(prime_list)

[11, 13, 23, 37, 47, 59, 61, 71, 73, 83, 97, 107, 109, 131]


In [3]:
G = generator_matrix(13,"N")
G = generator_matrix(13,"Q")

2
residues are {1, 3, 4, 9, 10, 12}
nonresidues are {2, 5, 6, 7, 8, 11}
extension field used = 3^3
root of unity used: 9
nonquadratic roots [GF(15, order=3^3), GF(12, order=3^3), GF(11, order=3^3), GF(6, order=3^3), GF(7, order=3^3), GF(8, order=3^3)]
coefficients are: [0 0 0 0 0 0 1 1 2 0 2 1 1]
[[0 0 0 0 0 0 1 1 2 0 2 1 1]
 [1 0 0 0 0 0 0 1 1 2 0 2 1]
 [1 1 0 0 0 0 0 0 1 1 2 0 2]
 [2 1 1 0 0 0 0 0 0 1 1 2 0]
 [0 2 1 1 0 0 0 0 0 0 1 1 2]
 [2 0 2 1 1 0 0 0 0 0 0 1 1]
 [1 2 0 2 1 1 0 0 0 0 0 0 1]
 [1 1 2 0 2 1 1 0 0 0 0 0 0]
 [0 1 1 2 0 2 1 1 0 0 0 0 0]
 [0 0 1 1 2 0 2 1 1 0 0 0 0]
 [0 0 0 1 1 2 0 2 1 1 0 0 0]
 [0 0 0 0 1 1 2 0 2 1 1 0 0]
 [0 0 0 0 0 1 1 2 0 2 1 1 0]]
2
residues are {1, 3, 4, 9, 10, 12}
nonresidues are {2, 5, 6, 7, 8, 11}
extension field used = 3^3
root of unity used: 9
quadratic roots [GF(9, order=3^3), GF(13, order=3^3), GF(20, order=3^3), GF(16, order=3^3), GF(22, order=3^3), GF(25, order=3^3)]
coefficients are: [0 0 0 0 0 0 1 0 2 2 2 0 1]
[[0 0 0 0 0 0 1 0 2 2 2 0 1

In [ ]:
for p in prime_list:
    G = generator_matrix(p,"Q",loud=True)
    if delta_divisible_np(G, 4,loud=True):
        print(f"code of length {p} is 2 divisible")

#print(min_distance_brute(G))

2
residues are {1, 34, 33, 4, 36, 3, 7, 9, 10, 11, 12, 16, 21, 25, 26, 27, 28, 30}
nonresidues are {2, 5, 6, 8, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, 29, 31, 32, 35}
extension field used = 3^18
root of unity used: 376253798
quadratic roots [GF(376253798, order=3^18), GF(11103006, order=3^18), GF(379912237, order=3^18), GF(186511695, order=3^18), GF(164766052, order=3^18), GF(24411610, order=3^18), GF(227320244, order=3^18), GF(153350641, order=3^18), GF(247440407, order=3^18), GF(180732155, order=3^18), GF(207758603, order=3^18), GF(363781367, order=3^18), GF(361035734, order=3^18), GF(379518564, order=3^18), GF(366984516, order=3^18), GF(292707976, order=3^18), GF(171330935, order=3^18), GF(351248106, order=3^18)]
coefficients are: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 2 0 2 2 0 1 0 0 0 1 0 2 2 0 2 0 1]
[[0 0 0 ... 2 0 1]
 [1 0 0 ... 0 2 0]
 [0 1 0 ... 2 0 2]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]]
[[1 2 0 ... 1 0 2]
 [2 1 2 ... 0 1 0]
 [0 2 1 ... 1 0 1]
 .

In [ ]:
print(min_distance_brute(extended_generator_matrix(23, base = "Nbar")))



5
residues are {1, 2, 3, 4, 6, 8, 9, 12, 13, 16, 18}
nonresidues are {5, 7, 10, 11, 14, 15, 17, 19, 20, 21, 22}
extension field used = 3^11
root of unity used: 38455
nonquadratic roots [GF(58455, order=3^11), GF(19713, order=3^11), GF(195, order=3^11), GF(342, order=3^11), GF(143112, order=3^11), GF(61173, order=3^11), GF(123882, order=3^11), GF(33804, order=3^11), GF(10053, order=3^11), GF(41823, order=3^11), GF(107973, order=3^11)]
coefficients are: [0 0 0 0 0 0 0 0 0 0 1 2 0 2 1 2 1 1 0 1 0 0 1]
[[0 0 0 0 0 0 0 0 0 0 1 2 0 2 1 2 1 1 0 1 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1 2 0 2 1 2 1 1 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 2 0 2 1 2 1 1 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 2 0 2 1 2 1 1 0 1]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 2 0 2 1 2 1 1 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 2 0 2 1 2 1 1]
 [1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 2 0 2 1 2 1]
 [1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 2 0 2 1 2]
 [2 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 2 0 2 1]
 [1 2 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 2 0 2]
 [2 1 

In [ ]:
G = generator_matrix(11, version="Qbar", loud=False)
print(np.asarray([[0, 0]]).shape)
print(G @ np.ones(11))

(1, 2)
[9. 9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]


In [ ]:
for p in prime_list:
    G = generator_matrix(p, "Nbar", loud=False)
    if triorthogonal(G, loud= False):
        print(f"code of length {p} is triorthogonal")

Checking second triorthogonality condition not done yet


NameError: name 'M64' is not defined

In [ ]:
# Checking properties
# weight mod 9, equality of 1s and 2s, num 1s and 2s
# nine div propogates
# equality of ones and twos also probably propogates

for p in prime_list:
    polynom